# Generated by Django - temporary file for merge
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('competition_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTextProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Hilfetext',
                'verbose_name_plural': 'Hilfetexte',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.helptext',),
        ),
        migrations.AlterModelOptions(
            name='competitionsettingsproxy',
            options={'verbose_name': 'Wettkampf-Einstellungen', 'verbose_name_plural': 'Wettkampf-Einstellungen'},
        ),
    ]
