# Generated by Django 5.2.8 on 2026-02-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_helptext_delete_rulebook'),
        ('competition_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettingsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Site-Einstellungen',
                'verbose_name_plural': 'Site-Einstellungen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.sitesettings',),
        ),
        migrations.AlterModelOptions(
            name='competitionsettingsproxy',
            options={'verbose_name': 'Punktesystem', 'verbose_name_plural': 'Punktesystem'},
        ),
    ]
