# Generated by Django - modified to remove references to deleted models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_helptext_delete_rulebook'),
        ('competition_admin', '0001_initial'),
    ]

    operations = [
        # HelpTextProxy creation removed - HelpText model was deleted in accounts.0011
        # Migration kept for historical consistency with production database
        migrations.AlterModelOptions(
            name='competitionsettingsproxy',
            options={'verbose_name': 'Wettkampf-Einstellungen', 'verbose_name_plural': 'Wettkampf-Einstellungen'},
        ),
    ]
