# Generated by Django 5.2.8 on 2025-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('competition_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulebookProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Regelwerk',
                'verbose_name_plural': 'Regelwerke',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.rulebook',),
        ),
    ]
