# Generated by Django 5.2.8 on 2025-12-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_admin', '0002_rulebookproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulebookproxy',
            options={'verbose_name': 'Regelwerk', 'verbose_name_plural': 'Regelwerk'},
        ),
    ]
