# Generated by Django 5.2.8 on 2026-02-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition_admin', '0002_delete_rulebookproxy_sitesettingsproxy_and_more'),
        ('competition_admin', '0002_helptextproxy_alter_competitionsettingsproxy_options'),
    ]

    operations = [
    ]
