# Generated by Django 5.2.8 on 2026-01-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionwindow',
            name='age_groups',
            field=models.ManyToManyField(blank=True, help_text='Altersgruppen, die in diesem Zeitfenster Ergebnisse eintragen dürfen.', related_name='submission_windows', to='accounts.agegroup'),
        ),
    ]
