# Generated by Django 5.2.8 on 2025-12-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulebook',
            options={'verbose_name': 'Regelwerk', 'verbose_name_plural': 'Regelwerk'},
        ),
    ]
