# Generated by Django 5.2.8 on 2025-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_participant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Kürzel oder Nummer, z.B. B12 oder A3.', max_length=30, unique=True)),
                ('color', models.CharField(help_text='Griff-/Tape-Farbe zur einfachen Zuordnung.', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Sektor/Zone (kann später als eigenes Modell ausgegliedert werden).', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
