# Generated by Django 5.2.8 on 2026-01-16 07:58

import django_ckeditor_5.fields
from django.db import migrations, models


def seed_helptext(apps, schema_editor):
    """Seed default help text."""
    HelpText = apps.get_model("accounts", "HelpText")
    if not HelpText.objects.exists():
        default_content = """
        <h2>Willkommen zur Hilfeseite!</h2>
        <p>Hier findest du Informationen und Ansprechpartner, falls du Hilfe benötigst.</p>
        <h3>Häufig gestellte Fragen</h3>
        <ul>
            <li><strong>Wie trage ich meine Ergebnisse ein?</strong><br>
            Gehe zu "Ergebnisse" und wähle die Boulder aus, die du geklettert bist.</li>
            <li><strong>Wann kann ich meine Ergebnisse eintragen?</strong><br>
            Die Ergebnisse können während des festgelegten Zeitfensters für deine Altersgruppe eingetragen werden.</li>
            <li><strong>Wo sehe ich die aktuelle Rangliste?</strong><br>
            Die Rangliste findest du unter "Rangliste".</li>
        </ul>
        <h3>Kontakt</h3>
        <p>Bei weiteren Fragen wende dich bitte an die Wettkampfleitung vor Ort.</p>
        """
        HelpText.objects.create(
            name="Hilfe & Support",
            content=default_content.strip(),
            singleton_guard=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_age_groups_to_submission_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hilfe & Support', max_length=150)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Hilfetext')),
                ('singleton_guard', models.BooleanField(default=True, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hilfetext',
                'verbose_name_plural': 'Hilfetexte',
            },
        ),
        migrations.RunPython(seed_helptext, reverse_code=migrations.RunPython.noop),
    ]
