# Generated by Django 5.2.8 on 2026-01-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_helptext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
