# Generated by Django 5.2.8 on 2025-12-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rulebook',
            options={'verbose_name': 'Regelwerk', 'verbose_name_plural': 'Regelwerke'},
        ),
        migrations.RenameIndex(
            model_name='agegroup',
            new_name='accounts_ag_min_age_a2e8f4_idx',
            old_name='accounts_ag_min_age_idx',
        ),
        migrations.RenameIndex(
            model_name='boulder',
            new_name='accounts_bo_label_8b7580_idx',
            old_name='accounts_bo_label_idx',
        ),
        migrations.RenameIndex(
            model_name='participant',
            new_name='accounts_pa_age_gro_461ba4_idx',
            old_name='accounts_pa_age_grp_idx',
        ),
        migrations.RenameIndex(
            model_name='participant',
            new_name='accounts_pa_usernam_5f4b9e_idx',
            old_name='accounts_pa_usernam_idx',
        ),
        migrations.RenameIndex(
            model_name='result',
            new_name='accounts_re_partici_c1dc6b_idx',
            old_name='accounts_re_part_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='result',
            new_name='accounts_re_boulder_b7e486_idx',
            old_name='accounts_re_bould_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='result',
            new_name='accounts_re_partici_26b273_idx',
            old_name='accounts_re_part_bou_idx',
        ),
    ]
