# Generated by Django 5.2.8 on 2025-11-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_boulder'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='age_groups',
            field=models.ManyToManyField(blank=True, help_text='Wähle alle Altersgruppen, für die dieser Boulder gedacht ist.', related_name='boulders', to='accounts.agegroup'),
        ),
    ]
