# Generated by Django 5.2.8 on 2026-01-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_participant_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, help_text='Titel der Nachricht (optional).', max_length=200, verbose_name='Überschrift')),
                ('content', models.TextField(blank=True, help_text='Nachrichteninhalt (optional).', verbose_name='Nachricht')),
                ('background_color', models.CharField(default='#ef4444', help_text='Hintergrundfarbe der Nachricht (Hex-Code, z.B. #ef4444).', max_length=7, verbose_name='Hintergrundfarbe')),
                ('singleton_guard', models.BooleanField(default=True, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin-Nachricht',
                'verbose_name_plural': 'Admin-Nachrichten',
            },
        ),
    ]
