# Generated by Django 5.2.8 on 2026-01-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Gesperrte Teilnehmer können sich nicht anmelden und werden nicht auf Ranglisten angezeigt.', verbose_name='Gesperrt'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['is_locked'], name='accounts_pa_is_lock_e19a00_idx'),
        ),
    ]
