# Generated by Django 5.2.8 on 2026-01-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_flash_points_default_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_10',
            field=models.PositiveIntegerField(default=50, help_text='Top-Punkte wenn 10% oder weniger der Teilnehmer den Boulder getoppt haben.', verbose_name='10%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_100',
            field=models.PositiveIntegerField(default=25, help_text='Top-Punkte wenn 100% der Teilnehmer den Boulder getoppt haben.', verbose_name='100%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_20',
            field=models.PositiveIntegerField(default=46, help_text='Top-Punkte wenn 20% der Teilnehmer den Boulder getoppt haben.', verbose_name='20%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_30',
            field=models.PositiveIntegerField(default=44, help_text='Top-Punkte wenn 30% der Teilnehmer den Boulder getoppt haben.', verbose_name='30%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_40',
            field=models.PositiveIntegerField(default=42, help_text='Top-Punkte wenn 40% der Teilnehmer den Boulder getoppt haben.', verbose_name='40%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_50',
            field=models.PositiveIntegerField(default=40, help_text='Top-Punkte wenn 50% der Teilnehmer den Boulder getoppt haben.', verbose_name='50%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_60',
            field=models.PositiveIntegerField(default=35, help_text='Top-Punkte wenn 60% der Teilnehmer den Boulder getoppt haben.', verbose_name='60%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_70',
            field=models.PositiveIntegerField(default=30, help_text='Top-Punkte wenn 70% der Teilnehmer den Boulder getoppt haben.', verbose_name='70%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_80',
            field=models.PositiveIntegerField(default=25, help_text='Top-Punkte wenn 80% der Teilnehmer den Boulder getoppt haben.', verbose_name='80%'),
        ),
        migrations.AddField(
            model_name='competitionsettings',
            name='top_points_90',
            field=models.PositiveIntegerField(default=25, help_text='Top-Punkte wenn 90% der Teilnehmer den Boulder getoppt haben.', verbose_name='90%'),
        ),
        migrations.AlterField(
            model_name='competitionsettings',
            name='grading_system',
            field=models.CharField(choices=[('ifsc', 'IFSC (Tops/Zones/Versuche)'), ('point_based', 'Punktebasiert'), ('point_based_dynamic', 'Punktebasiert (dynamisch)')], default='ifsc', max_length=20),
        ),
    ]
