# Generated by Django 5.2.8 on 2026-02-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_participant_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Site-Einstellungen', editable=False, max_length=150)),
                ('dashboard_heading', models.CharField(default='Willkommen beim BoulderCup', help_text='Überschrift auf der Startseite für Teilnehmer.', max_length=200, verbose_name='Dashboard-Überschrift')),
                ('singleton_guard', models.BooleanField(default=True, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site-Einstellung',
                'verbose_name_plural': 'Site-Einstellungen',
            },
        ),
    ]
