# Generated by Django 5.2.8 on 2026-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_dynamic_scoring_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsettings',
            name='grading_system',
            field=models.CharField(choices=[('ifsc', 'IFSC (Tops/Zones/Versuche)'), ('point_based', 'Punktebasiert'), ('point_based_dynamic', 'Punktebasiert (dynamisch)'), ('point_based_dynamic_attempts', 'Punktebasiert (dynamisch + Versuche)')], default='ifsc', max_length=30),
        ),
    ]
