# Generated by Django 5.2.8 on 2026-02-01 10:35

from django.db import migrations


def create_initial_site_settings(apps, schema_editor):
    """Create initial SiteSettings with default heading."""
    SiteSettings = apps.get_model('accounts', 'SiteSettings')
    if not SiteSettings.objects.exists():
        SiteSettings.objects.create(
            name="Site-Einstellungen",
            dashboard_heading="Willkommen beim BoulderCup"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sitesettings'),
    ]

    operations = [
        migrations.RunPython(create_initial_site_settings, migrations.RunPython.noop),
    ]
