# Generated by Django 5.2.8 on 2026-02-01 11:05

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20260201_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='greeting_message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nachricht, die Teilnehmer beim Login bestätigen müssen. Leer lassen, um keine Nachricht anzuzeigen.', verbose_name='Begrüßungsnachricht'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='greeting_version',
            field=models.IntegerField(default=1, editable=False, help_text='Wird automatisch erhöht, wenn die Begrüßungsnachricht geändert wird.', verbose_name='Nachrichtenversion'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='help_text_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Inhalt der Hilfe-Seite für Teilnehmer.', verbose_name='Hilfe & Support Inhalt'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rulebook_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Inhalt des Regelwerks für Teilnehmer.', verbose_name='Regelwerk Inhalt'),
        ),
        migrations.CreateModel(
            name='GreetingAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_version', models.IntegerField(default=0, help_text='Version der Begrüßungsnachricht, die der Teilnehmer bestätigt hat.', verbose_name='Bestätigte Version')),
                ('acknowledged_at', models.DateTimeField(auto_now=True, verbose_name='Bestätigt am')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greeting_acknowledgment', to='accounts.participant', verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Begrüßungsbestätigung',
                'verbose_name_plural': 'Begrüßungsbestätigungen',
            },
        ),
    ]
