# Generated by Django 5.2.8 on 2025-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_competitionsettings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsettings',
            name='grading_system',
            field=models.CharField(choices=[('ifsc', 'IFSC (Tops/Zones/Versuche)'), ('custom', 'Punktebasiert')], default='ifsc', max_length=20),
        ),
    ]
