# Generated by Django 5.2.8 on 2026-02-01 11:05

from django.db import migrations


def migrate_content_to_site_settings(apps, schema_editor):
    """Copy content from Rulebook and HelpText into SiteSettings."""
    SiteSettings = apps.get_model('accounts', 'SiteSettings')
    Rulebook = apps.get_model('accounts', 'Rulebook')
    HelpText = apps.get_model('accounts', 'HelpText')

    # Get or create SiteSettings
    site_settings = SiteSettings.objects.first()
    if not site_settings:
        site_settings = SiteSettings.objects.create(name="Site-Einstellungen")

    # Copy Rulebook content
    rulebook = Rulebook.objects.first()
    if rulebook and rulebook.content:
        site_settings.rulebook_content = rulebook.content

    # Copy HelpText content
    help_text = HelpText.objects.first()
    if help_text and help_text.content:
        site_settings.help_text_content = help_text.content

    site_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sitesettings_greeting_message_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_content_to_site_settings, migrations.RunPython.noop),
    ]
