# Generated by Django 5.2.8 on 2026-02-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20260201_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpText',
        ),
        migrations.DeleteModel(
            name='Rulebook',
        ),
    ]
