# Generated by Django 5.2.8 on 2026-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_helptext_delete_rulebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='greeting_heading',
            field=models.CharField(default='Willkommen!', help_text='Überschrift im Begrüßungsdialog.', max_length=200, verbose_name='Begrüßungs-Überschrift'),
        ),
    ]
