# Generated by Django 5.2.8 on 2026-02-01 12:40

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sitesettings_greeting_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='greeting_enabled',
            field=models.BooleanField(default=False, help_text='Begrüßungsnachricht beim Login anzeigen.', verbose_name='Begrüßung aktivieren'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='greeting_message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Nachricht, die Teilnehmer beim Login bestätigen müssen.', verbose_name='Begrüßungsnachricht'),
        ),
    ]
