# Generated by Django 5.2.8 on 2026-02-01 12:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sitesettings_greeting_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='rulebook_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='<h2>Sicherheitsregeln</h2>\n<ul>\n<li>Achte auf andere Kletterer und halte ausreichend Abstand</li>\n<li>Klettere nicht unter anderen Teilnehmern</li>\n<li>Springe kontrolliert ab und achte auf die Landezone</li>\n<li>Nutze die Matten ordnungsgemäß</li>\n<li>Bei Verletzungen oder Problemen wende dich sofort an das Personal</li>\n</ul>\n\n<h2>Verhaltensregeln</h2>\n<ul>\n<li>Kein Beta-Sharing während des Wettbewerbs</li>\n<li>Respektiere andere Teilnehmer und das Personal</li>\n<li>Halte den Wettkampfbereich sauber</li>\n<li>Folge den Anweisungen des Personals</li>\n</ul>\n\n<h2>Wertungssystem</h2>\n<p><em>Die spezifischen Regeln zum Wertungssystem werden vom Veranstalter bekanntgegeben.</em></p>', help_text='Inhalt des Regelwerks für Teilnehmer.', verbose_name='Regelwerk Inhalt'),
        ),
    ]
