# Generated by Django 5.2.8 on 2026-02-01 12:46

from django.db import migrations


def populate_default_rulebook(apps, schema_editor):
    """Populate empty rulebook_content with default rules."""
    SiteSettings = apps.get_model('accounts', 'SiteSettings')

    default_rulebook = """<h2>Sicherheitsregeln</h2>
<ul>
<li>Achte auf andere Kletterer und halte ausreichend Abstand</li>
<li>Klettere nicht unter anderen Teilnehmern</li>
<li>Springe kontrolliert ab und achte auf die Landezone</li>
<li>Nutze die Matten ordnungsgemäß</li>
<li>Bei Verletzungen oder Problemen wende dich sofort an das Personal</li>
</ul>

<h2>Verhaltensregeln</h2>
<ul>
<li>Kein Beta-Sharing während des Wettbewerbs</li>
<li>Respektiere andere Teilnehmer und das Personal</li>
<li>Halte den Wettkampfbereich sauber</li>
<li>Folge den Anweisungen des Personals</li>
</ul>

<h2>Wertungssystem</h2>
<p><em>Die spezifischen Regeln zum Wertungssystem werden vom Veranstalter bekanntgegeben.</em></p>"""

    for settings in SiteSettings.objects.all():
        if not settings.rulebook_content:
            settings.rulebook_content = default_rulebook
            settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_sitesettings_rulebook_content'),
    ]

    operations = [
        migrations.RunPython(populate_default_rulebook, migrations.RunPython.noop),
    ]
