# Generated by Django 5.2.8 on 2026-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_sitesettings_rulebook_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsettings',
            name='grading_system',
            field=models.CharField(choices=[('ifsc', 'IFSC (Tops/Zones/Versuche)'), ('point_based', 'Punktebasiert'), ('point_based_dynamic', 'Punktebasiert (dynamisch)'), ('point_based_dynamic_attempts', 'Punktebasiert (dynamisch + Versuche)')], default='point_based', max_length=30),
        ),
    ]
