# Generated by Django 5.2.9 on 2026-02-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_competitionsettings_grading_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsettings',
            name='competition_date',
            field=models.DateField(blank=True, help_text='Datum des Wettkampfes für Altersberechnung. Falls leer, wird das aktuelle Datum verwendet.', null=True, verbose_name='Wettkampfdatum'),
        ),
    ]
