# Generated by Django 5.2.8 on 2026-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_competitionsettings_competition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boulder',
            name='color',
            field=models.CharField(help_text='Griff-/Tape-Farbe zur einfachen Zuordnung. Eingabe möglich als: Deutsche Namen (rot, blau, grün, türkis), Englische CSS-Namen (red, blue, hotpink), oder Hex-Codes (#ff0000, f00). Nicht-Standard-Farben werden automatisch auf die nächste CSS-Standardfarbe normalisiert.', max_length=50),
        ),
    ]
