# Generated by Django 5.2.8 on 2026-02-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_result_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punktesystem',
            fields=[
            ],
            options={
                'verbose_name': 'Punktesystem',
                'verbose_name_plural': 'Punktesystem',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.competitionsettings',),
        ),
        migrations.CreateModel(
            name='Wettkampfdatum',
            fields=[
            ],
            options={
                'verbose_name': 'Wettkampfdatum',
                'verbose_name_plural': 'Wettkampfdaten',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.competitionsettings',),
        ),
        migrations.AlterModelOptions(
            name='submissionwindow',
            options={'verbose_name': 'Zeitslot', 'verbose_name_plural': 'Zeitslots'},
        ),
    ]
