# Generated by Django 5.2.8 on 2026-02-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_proxy_models_and_rename_submission_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Countdown-Einstellungen', editable=False, max_length=150)),
                ('enabled', models.BooleanField(default=False, help_text='Zeigt allen Besuchern eine Countdown-Seite.', verbose_name='Countdown aktivieren')),
                ('countdown_end_time', models.DateTimeField(blank=True, help_text='Zeitpunkt, zu dem die normale Seite sichtbar wird.', null=True, verbose_name='Countdown endet am')),
                ('logo_url', models.URLField(blank=True, help_text='URL zum Logo-Bild (z.B. /static/img/logo.png)', verbose_name='Logo URL')),
                ('heading', models.CharField(default='BoulderCup', max_length=200, verbose_name='Hauptüberschrift')),
                ('subtitle', models.CharField(blank=True, help_text="z.B. 'Saison 2026'", max_length=200, verbose_name='Untertitel')),
                ('message', models.CharField(default='Coming Soon', max_length=100, verbose_name='Coming Soon Text')),
                ('background_color', models.CharField(default='#d4b896', help_text='Beige/Tan für BoulderCup', max_length=7, verbose_name='Hintergrundfarbe')),
                ('primary_color', models.CharField(default='#0c4d5c', help_text='Farbe für Squares 1 & 3', max_length=7, verbose_name='Primärfarbe (Teal)')),
                ('secondary_color', models.CharField(default='#a0622f', help_text='Farbe für Squares 2 & 4', max_length=7, verbose_name='Sekundärfarbe (Brown)')),
                ('singleton_guard', models.BooleanField(default=True, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Countdown-Einstellung',
                'verbose_name_plural': 'Countdown-Einstellungen',
            },
        ),
    ]
