# Generated by Django 5.2.8 on 2026-02-23 21:18

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_countdownsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdownsettings',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='countdownsettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Optional: Hintergrundbild hochladen (überschreibt Hintergrundfarbe)', null=True, upload_to='countdown/', verbose_name='Hintergrundbild'),
        ),
        migrations.AddField(
            model_name='countdownsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo-Bild hochladen', null=True, upload_to='countdown/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='countdownsettings',
            name='background_color',
            field=models.CharField(default='#d4b896', help_text='Fallback wenn kein Hintergrundbild gesetzt', max_length=7, verbose_name='Hintergrundfarbe'),
        ),
        migrations.AlterField(
            model_name='countdownsettings',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='<p>Coming Soon</p>', help_text='HTML-formatierte Nachricht mit WYSIWYG-Editor', verbose_name='Coming Soon Nachricht'),
        ),
    ]
