# Generated by Django 5.2.8 on 2026-02-23 21:24

from django.db import migrations


def create_default_countdown_settings(apps, schema_editor):
    """Create a default CountdownSettings instance (disabled)."""
    CountdownSettings = apps.get_model('accounts', 'CountdownSettings')

    # Only create if no settings exist
    if not CountdownSettings.objects.exists():
        CountdownSettings.objects.create(
            name="Countdown-Einstellungen",
            enabled=False,  # Disabled by default
            heading="BoulderCup",
            subtitle="",
            message="<p>Coming Soon</p>",
            background_color="#f1f5f9",
            primary_color="#1f7a8c",
            secondary_color="#166470",
            singleton_guard=True,
        )


def reverse_create_default(apps, schema_editor):
    """Remove the default CountdownSettings instance."""
    CountdownSettings = apps.get_model('accounts', 'CountdownSettings')
    CountdownSettings.objects.filter(singleton_guard=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_countdownsettings_logo_url_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_countdown_settings, reverse_create_default),
    ]
