# Generated by Django 5.2.8 on 2026-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_create_default_countdown_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdownsettings',
            name='background_color',
            field=models.CharField(default='#f1f5f9', help_text='Fallback wenn kein Hintergrundbild gesetzt (Standard: #f1f5f9)', max_length=7, verbose_name='Hintergrundfarbe'),
        ),
        migrations.AlterField(
            model_name='countdownsettings',
            name='primary_color',
            field=models.CharField(default='#1f7a8c', help_text='Farbe für Squares 1 & 3 (Standard: #1f7a8c)', max_length=7, verbose_name='Primärfarbe (Teal)'),
        ),
        migrations.AlterField(
            model_name='countdownsettings',
            name='secondary_color',
            field=models.CharField(default='#166470', help_text='Farbe für Squares 2 & 4 (Standard: #166470)', max_length=7, verbose_name='Sekundärfarbe (Dunkleres Teal)'),
        ),
    ]
