# Generated by Django 5.2.8 on 2026-02-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_countdownsettings_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdownsettings',
            name='primary_color',
            field=models.CharField(default='#1f7a8c', help_text='Farbe für Squares 1 & 3 (Standard: #1f7a8c)', max_length=7, verbose_name='Primärfarbe'),
        ),
        migrations.AlterField(
            model_name='countdownsettings',
            name='secondary_color',
            field=models.CharField(default='#166470', help_text='Farbe für Squares 2 & 4 (Standard: #166470)', max_length=7, verbose_name='Sekundärfarbe'),
        ),
    ]
