# Generated by Django 5.2.8 on 2026-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_countdownsettings_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdownsettings',
            name='show_preview_button',
            field=models.BooleanField(default=True, help_text='Erlaubt Admins, die Seite hinter dem Countdown vorab zu sehen.', verbose_name="'Preview Site'-Button anzeigen"),
        ),
    ]
