# Generated by Django 5.2.8 on 2026-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_fix_result_updated_at_no_auto_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='submission_always_open',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, können alle Teilnehmer jederzeit Ergebnisse einreichen – unabhängig von Zeitfenstern.', verbose_name='Abgabe dauerhaft offen'),
        ),
    ]
