# Generated by Django 5.2.8 on 2026-05-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_submission_always_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='boulder',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Reihenfolge innerhalb des Standorts (aufsteigend).'),
        ),
        migrations.AlterField(
            model_name='boulder',
            name='location',
            field=models.CharField(blank=True, choices=[('outside', 'Außen'), ('inside_eg', 'Innen EG'), ('inside_og', 'Innen OG')], default='', help_text='Bereich, in dem sich der Boulder befindet.', max_length=20),
        ),
    ]
